version: "3"

services:
  app-mysql:
    image: mysql:5.7.26
    container_name: app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    volumes:
      - app-mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=16M
    restart: always
    ports:
      - "3306:3306"

volumes:
  app-mysql: